from fastapi import APIRouter

from app.api.v1 import (
    access,
    admin_clients,
    analytics,
    assets,
    audit,
    auth,
    billing,
    changes,
    chatbot,
    credits,
    dashboard,
    documents,
    domains,
    exports,
    health,
    internal,
    invoices,
    leads,
    metrics,
    notifications,
    payments,
    portal,
    publishing,
    seo,
    sites,
    tenants,
    webhooks,
)

api_router = APIRouter()
api_router.include_router(health.router)
api_router.include_router(metrics.router)
api_router.include_router(auth.router)
api_router.include_router(access.router)
api_router.include_router(admin_clients.router)
api_router.include_router(dashboard.router)
api_router.include_router(tenants.router)
api_router.include_router(sites.router)
api_router.include_router(publishing.router)
api_router.include_router(leads.router)
api_router.include_router(credits.router)
api_router.include_router(notifications.router)
api_router.include_router(domains.router)
api_router.include_router(payments.router)
api_router.include_router(invoices.router)
api_router.include_router(billing.router)
api_router.include_router(exports.router)
api_router.include_router(documents.router)
api_router.include_router(chatbot.router)
api_router.include_router(seo.router)
api_router.include_router(analytics.router)
api_router.include_router(assets.router)
api_router.include_router(changes.router)
api_router.include_router(audit.router)
api_router.include_router(portal.router)
api_router.include_router(internal.router)
api_router.include_router(webhooks.router)
