"""explicit production schema

Revision ID: 07d641d8e2ec
Revises: 
Create Date: 2026-07-16 19:15:31.579337
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '07d641d8e2ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.String(length=120), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_session_id'), 'analytics_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_site_id'), 'analytics_events', ['site_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_tenant_id'), 'analytics_events', ['tenant_id'], unique=False)
    op.create_index('ix_analytics_tenant_type_created', 'analytics_events', ['tenant_id', 'event_type', 'created_at'], unique=False)
    op.create_table('api_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=False),
    sa.Column('secret_last_four', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', name='uq_api_credential_provider')
    )
    op.create_index(op.f('ix_api_credentials_tenant_id'), 'api_credentials', ['tenant_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('detected_mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scan_status', sa.String(length=30), nullable=False),
    sa.Column('scan_provider', sa.String(length=40), nullable=True),
    sa.Column('scan_details', sa.JSON(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_url', sa.String(length=1000), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_assets_tenant_created', 'assets', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('change_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'QUOTED', 'APPROVED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='changerequeststatus'), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('quoted_price_minor', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_requests_tenant_id'), 'change_requests', ['tenant_id'], unique=False)
    op.create_table('chat_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('visitor_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversations_site_id'), 'chat_conversations', ['site_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_tenant_id'), 'chat_conversations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_visitor_id'), 'chat_conversations', ['visitor_id'], unique=False)
    op.create_table('client_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'CLIENT_ADMIN', 'CLIENT_VIEWER', name='membershiprole'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('accepted_user_id', sa.Uuid(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_invitation_token_hash')
    )
    op.create_index(op.f('ix_client_invitations_email'), 'client_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_client_invitations_tenant_id'), 'client_invitations', ['tenant_id'], unique=False)
    op.create_index('ix_invitation_tenant_status', 'client_invitations', ['tenant_id', 'status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'READY', 'FAILED', name='documentstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_table('feature_flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('configuration_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_feature_flag')
    )
    op.create_index(op.f('ix_feature_flags_tenant_id'), 'feature_flags', ['tenant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PAID', 'VOID', 'OVERDUE', name='invoicestatus'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal_minor', sa.Integer(), nullable=False),
    sa.Column('tax_minor', sa.Integer(), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', name='uq_invoice_number')
    )
    op.create_index(op.f('ix_invoices_number'), 'invoices', ['number'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('notification_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('business_enabled', sa.Boolean(), nullable=False),
    sa.Column('visitor_enabled', sa.Boolean(), nullable=False),
    sa.Column('business_template', sa.String(length=120), nullable=False),
    sa.Column('visitor_template', sa.String(length=120), nullable=False),
    sa.Column('business_charge_micro_usd', sa.Integer(), nullable=False),
    sa.Column('visitor_charge_micro_usd', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_notification_tenant')
    )
    op.create_index(op.f('ix_notification_settings_tenant_id'), 'notification_settings', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True),
    sa.Column('provider_order_id', sa.String(length=255), nullable=True),
    sa.Column('pack_id', sa.String(length=40), nullable=True),
    sa.Column('charged_amount_minor', sa.Integer(), nullable=False),
    sa.Column('charged_currency', sa.String(length=3), nullable=False),
    sa.Column('usd_credit_micro_amount', sa.Integer(), nullable=False),
    sa.Column('settlement_amount_inr_minor', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('checkout_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_order_id', name='uq_provider_order'),
    sa.UniqueConstraint('provider', 'provider_payment_id', name='uq_provider_payment')
    )
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_index('ix_payments_tenant_status', 'payments', ['tenant_id', 'status'], unique=False)
    op.create_table('seo_audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='seoauditstatus'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('issues_json', sa.JSON(), nullable=False),
    sa.Column('recommendations_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_audits_site_id'), 'seo_audits', ['site_id'], unique=False)
    op.create_index(op.f('ix_seo_audits_tenant_id'), 'seo_audits', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_seo_audits_version_id'), 'seo_audits', ['version_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('legal_name', sa.String(length=220), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('owner_name', sa.String(length=180), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_webhook_provider_event')
    )
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_provider'), 'webhook_events', ['provider'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_tenant_id'), 'chat_messages', ['tenant_id'], unique=False)
    op.create_table('credit_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance_micro_usd', sa.Integer(), nullable=False),
    sa.Column('reserved_micro_usd', sa.Integer(), nullable=False),
    sa.Column('low_balance_threshold_micro_usd', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'currency', name='uq_credit_account_currency')
    )
    op.create_index(op.f('ix_credit_accounts_tenant_id'), 'credit_accounts', ['tenant_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_tenant_id'), 'document_chunks', ['tenant_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('template_key', sa.String(length=80), nullable=False),
    sa.Column('draft_version_id', sa.Uuid(), nullable=True),
    sa.Column('published_version_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_tenant_id'), 'sites', ['tenant_id'], unique=False)
    op.create_table('tenant_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'CLIENT_ADMIN', 'CLIENT_VIEWER', name='membershiprole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_membership_tenant_user')
    )
    op.create_index(op.f('ix_tenant_memberships_email'), 'tenant_memberships', ['email'], unique=False)
    op.create_index(op.f('ix_tenant_memberships_tenant_id'), 'tenant_memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_memberships_user_id'), 'tenant_memberships', ['user_id'], unique=False)
    op.create_table('credit_reservations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('credit_account_id', sa.Uuid(), nullable=False),
    sa.Column('amount_micro_usd', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_type', sa.String(length=60), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credit_account_id'], ['credit_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_reservation_key')
    )
    op.create_index(op.f('ix_credit_reservations_credit_account_id'), 'credit_reservations', ['credit_account_id'], unique=False)
    op.create_index(op.f('ix_credit_reservations_tenant_id'), 'credit_reservations', ['tenant_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('credit_account_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('PURCHASE', 'DEDUCTION', 'RESERVATION', 'RELEASE', 'REFUND', 'ADJUSTMENT', name='credittransactiontype'), nullable=False),
    sa.Column('amount_micro_usd', sa.Integer(), nullable=False),
    sa.Column('balance_after_micro_usd', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credit_account_id'], ['credit_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_credit_transaction_idempotency')
    )
    op.create_index(op.f('ix_credit_transactions_credit_account_id'), 'credit_transactions', ['credit_account_id'], unique=False)
    op.create_index('ix_credit_transactions_tenant_created', 'credit_transactions', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_credit_transactions_tenant_id'), 'credit_transactions', ['tenant_id'], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('domain_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFYING', 'ACTIVE', 'EXPIRING', 'EXPIRED', 'FAILED', name='domainstatus'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('registered_to_client', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renewal_price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_reminder_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_index(op.f('ix_domains_site_id'), 'domains', ['site_id'], unique=False)
    op.create_index(op.f('ix_domains_tenant_id'), 'domains', ['tenant_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('service', sa.String(length=180), nullable=True),
    sa.Column('preferred_contact', sa.String(length=30), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('whatsapp_consent', sa.Boolean(), nullable=False),
    sa.Column('marketing_consent', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'FOLLOW_UP', 'CONVERTED', 'LOST', 'SPAM', name='leadstatus'), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_site_id'), 'leads', ['site_id'], unique=False)
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_index('ix_leads_tenant_status_created', 'leads', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_table('site_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY_FOR_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'PUBLISHING', 'PUBLISHED', 'ARCHIVED', name='siteversionstatus'), nullable=False),
    sa.Column('content_snapshot', sa.JSON(), nullable=False),
    sa.Column('theme_snapshot', sa.JSON(), nullable=False),
    sa.Column('seo_snapshot', sa.JSON(), nullable=False),
    sa.Column('validation_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'version_number', name='uq_site_version_number')
    )
    op.create_index(op.f('ix_site_versions_site_id'), 'site_versions', ['site_id'], unique=False)
    op.create_index(op.f('ix_site_versions_tenant_id'), 'site_versions', ['tenant_id'], unique=False)
    op.create_index('ix_site_versions_tenant_status', 'site_versions', ['tenant_id', 'status'], unique=False)
    op.create_table('lead_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_notes_lead_id'), 'lead_notes', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_notes_tenant_id'), 'lead_notes', ['tenant_id'], unique=False)
    op.create_table('notification_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_type', sa.String(length=30), nullable=False),
    sa.Column('recipient', sa.String(length=80), nullable=False),
    sa.Column('template_name', sa.String(length=120), nullable=False),
    sa.Column('template_language', sa.String(length=10), nullable=False),
    sa.Column('template_variables', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CREDIT_RESERVED', 'SUBMITTED', 'DELIVERED', 'READ', 'FAILED', 'SKIPPED_INSUFFICIENT_CREDITS', 'SKIPPED_NO_CONSENT', 'SKIPPED_DISABLED', 'REFUNDED', name='notificationstatus'), nullable=False),
    sa.Column('charge_micro_usd', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('provider_status', sa.String(length=40), nullable=True),
    sa.Column('provider_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_notification_idempotency')
    )
    op.create_index(op.f('ix_notification_jobs_lead_id'), 'notification_jobs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_notification_jobs_tenant_id'), 'notification_jobs', ['tenant_id'], unique=False)
    op.create_index('ix_notification_status_created', 'notification_jobs', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_status_created', table_name='notification_jobs')
    op.drop_index(op.f('ix_notification_jobs_tenant_id'), table_name='notification_jobs')
    op.drop_index(op.f('ix_notification_jobs_lead_id'), table_name='notification_jobs')
    op.drop_table('notification_jobs')
    op.drop_index(op.f('ix_lead_notes_tenant_id'), table_name='lead_notes')
    op.drop_index(op.f('ix_lead_notes_lead_id'), table_name='lead_notes')
    op.drop_table('lead_notes')
    op.drop_index('ix_site_versions_tenant_status', table_name='site_versions')
    op.drop_index(op.f('ix_site_versions_tenant_id'), table_name='site_versions')
    op.drop_index(op.f('ix_site_versions_site_id'), table_name='site_versions')
    op.drop_table('site_versions')
    op.drop_index('ix_leads_tenant_status_created', table_name='leads')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_site_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_domains_tenant_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_site_id'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_credit_transactions_tenant_id'), table_name='credit_transactions')
    op.drop_index('ix_credit_transactions_tenant_created', table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_credit_account_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_credit_reservations_tenant_id'), table_name='credit_reservations')
    op.drop_index(op.f('ix_credit_reservations_credit_account_id'), table_name='credit_reservations')
    op.drop_table('credit_reservations')
    op.drop_index(op.f('ix_tenant_memberships_user_id'), table_name='tenant_memberships')
    op.drop_index(op.f('ix_tenant_memberships_tenant_id'), table_name='tenant_memberships')
    op.drop_index(op.f('ix_tenant_memberships_email'), table_name='tenant_memberships')
    op.drop_table('tenant_memberships')
    op.drop_index(op.f('ix_sites_tenant_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_document_chunks_tenant_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_credit_accounts_tenant_id'), table_name='credit_accounts')
    op.drop_table('credit_accounts')
    op.drop_index(op.f('ix_chat_messages_tenant_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_webhook_events_provider'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_seo_audits_version_id'), table_name='seo_audits')
    op.drop_index(op.f('ix_seo_audits_tenant_id'), table_name='seo_audits')
    op.drop_index(op.f('ix_seo_audits_site_id'), table_name='seo_audits')
    op.drop_table('seo_audits')
    op.drop_index('ix_payments_tenant_status', table_name='payments')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_notification_settings_tenant_id'), table_name='notification_settings')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_feature_flags_tenant_id'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_invitation_tenant_status', table_name='client_invitations')
    op.drop_index(op.f('ix_client_invitations_tenant_id'), table_name='client_invitations')
    op.drop_index(op.f('ix_client_invitations_email'), table_name='client_invitations')
    op.drop_table('client_invitations')
    op.drop_index(op.f('ix_chat_conversations_visitor_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_tenant_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_site_id'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.drop_index(op.f('ix_change_requests_tenant_id'), table_name='change_requests')
    op.drop_table('change_requests')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_index('ix_assets_tenant_created', table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_api_credentials_tenant_id'), table_name='api_credentials')
    op.drop_table('api_credentials')
    op.drop_index('ix_analytics_tenant_type_created', table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_tenant_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_site_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_session_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
