port 0
tls-port 6379
tls-cert-file /run/secrets/redis_server_crt
tls-key-file /run/secrets/redis_server_key
tls-ca-cert-file /run/secrets/redis_ca_crt
tls-auth-clients no
appendonly yes
protected-mode yes
